version: '3'

services:
  docker-mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
    - 3306:3306
    expose:
    - 3306
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=test_bank
  spring-boot-jpa-docker-webapp:
    image: test-bank-api:0.1.0
    container_name: test-bank-api
    depends_on:
    - docker-mysql
    ports:
    - 8080:8080
    expose:
    - 8080
    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_NAME=test_bank
    - DATABASE_USER=root
    - MYSQL_ROOT_PASSWORD=admin
    - DATABASE_PORT=3306
    links:
    - docker-mysql