spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/test_bank
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

---
spring:
  profiles: prod
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://mysql:3306/test_bank
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql